// === Palabras clave por tema ===
const PalabrasClave = {
    calidad_aire: ["aire", "pureza", "calidad", "respirar", "oxígeno", "índice", "aqi", "pm2.5", "partículas"],
    contaminacion: ["smog", "humo", "emisiones", "fósiles", "industria", "combustibles", "pm10", "ozono", "so2"],
    purificacion_aire: ["purificar", "filtrar", "hepa", "carbon", "ionizador", "ventilacion", "plantas", "uv", "fotocatalisis"],
    dispositivo_airguard: ["airguard", "sensor", "pms5003", "mq-7", "bme688", "iot", "mantenimiento", "esp32", "firebase"],
    salud_medio_ambiente: ["asma", "epoc", "alergia", "salud", "vulnerables", "ojos", "toxinas", "enfermedades", "bebé", "daño"],
    consejos_ecologicos: ["reciclar", "ahorrar", "ecologico", "reducir", "sostenible", "transporte", "hogar", "reutilizar", "consumo"],
    educacion_ecologica: ["ecologia", "biodiversidad", "carbono", "clima", "invernadero", "definicion", "huella", "ciclo", "modelos"],
    cordialidad: ["hola", "gracias", "adios", "saludos", "hasta luego", "te agradezco", "me ayudaste"]
};

// === Palabras por subtema ===
const PalabrasPorSubtema = {
    "Agricultura y Ganadería": ["actividades", "afectan", "agricultura", "agrícolas", "aire", "alimentar", "alta", "amoníaco", "animales", "análisis"],
    "Ahorro de energía en casa": ["acondicionado", "además", "afecta", "afectar", "agua", "ahorrar", "ahorro", "aire", "alta", "ambiental"],
    "Alergias Respiratorias": ["afecta", "agentes", "agrava", "aire", "alergia", "alergias", "alta", "alto", "altos", "alérgenos"],
    "Alertas y notificaciones": ["acción", "activa", "actuar", "adultos", "aire", "airguard", "ajusta", "ajustar", "alerta", "alertas"],
    "Arquitectura IoT": ["actualizar", "aire", "airguard", "alergias", "alertas", "altos", "ambientales", "aplicación", "arquitectura", "asegurar"],
    "Asma y EPOC": ["acciones", "acelerar", "actividades", "afecta", "aire", "airguard", "alertas", "altos", "ambiental", "ambiente"],
    "Beneficios de la Mejora del Aire": ["acciones", "aerosoles", "aire", "ambientales", "ambiente", "ambientes", "apps", "asma", "ataques", "automóvil"],
    "Biodiversidad": ["acciones", "aceite", "actualmente", "agua", "aire", "alimentos", "alta", "ambiental", "ambientales", "animales"],
    "Cambio Climático": ["acciones", "acción", "actividad", "afecta", "alimentaria", "alteración", "ambiental", "ambiente", "apoya", "aumento"],
    "Carbón Activado": ["activado", "adsorción", "aire", "ambiente", "ambientes", "atrapa", "atrapados", "atrapar", "ayuda", "filtro"],
    "Ciclo del Carbono": ["absorbe", "absorber", "acciones", "actividades", "aire", "algunos", "alimentos", "animales", "apoyar", "atmósfera"],
    "Compuestos Orgánicos Volátiles (COV)": ["compuestos", "volátiles", "cocina", "detectar", "aire", "químicos", "ambiente", "emisiones", "productos", "toxicidad"],
    "Conectividad y sincronización": ["iot", "internet", "dispositivo", "sincronización", "actualización", "wifi", "airguard", "app", "red", "monitoreo"],
    "Consumo Responsable": ["reducir", "reutilizar", "evitar", "hogar", "sostenible", "productos", "desechables", "ecológico", "comportamiento", "hábitos"],
    "Contaminación Doméstica": ["hogar", "ambientadores", "químicos", "cocinar", "aire", "velas", "productos", "cerrado", "inhalar", "exposición"],
    "Contaminación cruzada urbano-rural": ["rural", "urbano", "cruzada", "zonas", "mezcla", "aire", "ambientes", "fuentes", "transporte", "industria"],
    "Contaminación en interiores": ["interiores", "cerrados", "hogar", "ventilación", "filtración", "aire", "contaminación", "purificador", "ambiente", "exposición"],
    "Contaminación prenatal": ["embarazadas", "prenatal", "feto", "gestación", "recién", "nacido", "bebés", "daño", "exposición", "riesgo"],
    "Definiciones Básicas": ["definición", "concepto", "clave", "básico", "significado", "entender", "fundamentos", "base", "pm2.5", "contaminación"],
    "Dióxido de Azufre (SO₂)": ["azufre", "dióxido", "so2", "aire", "químico", "contaminante", "gases", "industria", "emisiones", "respirar"],
    "Dióxido de Nitrógeno (NO₂)": ["nitrógeno", "dióxido", "no2", "químico", "gases", "vehículos", "aire", "oxígeno", "respirar", "contaminante"],
    "Economía Circular": ["reutilización", "reciclaje", "consumo", "sostenible", "productos", "residuos", "materiales", "recursos", "aprovechar", "reducir"],
    "Efecto Invernadero": ["efecto", "gases", "atrapan", "calor", "atmósfera", "invernadero", "co2", "radiación", "temperatura", "clima"],
    "Efectos a Largo Plazo": ["humo", "crónica", "pulmones", "exposición", "constante", "aire", "enfermedad", "daño", "riesgo", "cardiovascular"],
    "Efectos en el Clima": ["clima", "alteraciones", "temperatura", "precipitaciones", "patrones", "aumento", "cambio", "atmósfera", "invernadero", "ozono"],
    "Efectos en la fauna": ["mascotas", "perros", "gatos", "fauna", "animales", "aire", "contaminación", "daño", "exposición", "enfermedad"],
    "Elección de productos no tóxicos": ["productos", "no", "tóxicos", "etiquetas", "sustancias", "seguro", "hogar", "limpieza", "químicos", "exposición"],
    "Emisiones Industriales": ["emisiones", "industria", "contaminación", "fábricas", "humo", "chimeneas", "procesos", "materiales", "aire", "so2"],
    "Enfermedades Cardiovasculares": ["cardiovascular", "corazón", "circulación", "presión", "daño", "aire", "contaminación", "enfermedad", "riesgo", "salud"],
    "Estaciones de monitoreo ambiental": ["monitoreo", "estaciones", "datos", "sensor", "calidad", "registro", "ambiente", "red", "tiempo", "medición"],
    "Filtros HEPA": ["hepa", "filtro", "captura", "micrón", "eficiencia", "retención", "partículas", "mecánico", "purificador", "aire"],
    "Grupos Vulnerables": ["niños", "ancianos", "embarazadas", "vulnerables", "riesgo", "asma", "enfermedad", "sensibles", "pulmones", "exposición"],
    "Huella de Carbono": ["huella", "carbono", "co2", "impacto", "consumo", "emisiones", "reducir", "actividad", "transporte", "ambiente"],
    "Impacto en áreas urbanas y rurales": ["urbana", "rural", "zonas", "ciudad", "campo", "contaminación", "aire", "población", "fuentes", "condiciones"],
    "Incendios Forestales": ["incendio", "forestal", "bosques", "quema", "humo", "aire", "emisión", "partículas", "naturaleza", "sequía"],
    "Interfaz web y app móvil": ["interfaz", "web", "aplicación", "móvil", "usuario", "panel", "visualizar", "historial", "datos", "dispositivo"],
    "Interpretación de datos ambientales": ["datos", "mediciones", "análisis", "gráficas", "valores", "tendencias", "lecturas", "resultados", "niveles", "comparaciones"],
    "Ionizadores": ["ionizador", "iones", "eléctrico", "ionización", "polaridad", "partículas", "aire", "negativos", "ambiente", "filtrar"],
    "Irritación Ocular": ["ojos", "picazón", "lagrimeo", "enrojecimiento", "ardor", "exposición", "aire", "partículas", "alergia", "contaminación"],
    "Mantenimiento de dispositivos purificadores": ["mantenimiento", "limpieza", "revisión", "filtro", "estado", "funcionamiento", "aire", "purificador", "intervalos", "sensor"],
    "Mantenimiento de vehículos": ["vehículo", "motor", "afinación", "emisión", "mantenimiento", "escape", "combustible", "revisión", "aire", "contaminación"],
    "Microcontaminantes": ["partículas", "ultrafinas", "toxicidad", "volátiles", "reacciones", "compuestos", "exposición", "daño", "orgánicos", "gases"],
    "Monitoreo en tiempo real": ["tiempo", "real", "datos", "actualización", "alertas", "lecturas", "sensor", "continuo", "aire", "ambiente"],
    "Monóxido de Carbono (CO)": ["monóxido", "carbono", "co", "sensor", "gas", "emisión", "toxicidad", "hogar", "combustión", "exposición"],
    "Normativas de calidad del aire": ["normas", "leyes", "regulación", "niveles", "limites", "calidad", "referencia", "estándar", "contaminante", "autoridades"],
    "ODS (Objetivos de Desarrollo Sostenible)": ["sostenible", "objetivos", "desarrollo", "meta", "ambiente", "energía", "cambio", "reducción", "ciudad", "igualdad"],
    "Ozono (O₃)": ["ozono", "gases", "fotoquímica", "o3", "estrato", "troposférico", "ultravioleta", "aire", "oxidante", "contaminación"],
    "PM10": ["pm10", "partículas", "gruesas", "diámetro", "respiratorias", "aire", "suspensión", "medición", "contaminación", "sensor"],
    "PM2.5": ["pm2.5", "partículas", "finas", "diámetro", "aerodinámico", "aire", "contaminación", "sensor", "toxicidad", "nivel"],
    "Plantar Árboles": ["plantar", "árboles", "reforestación", "verde", "naturaleza", "beneficios", "sombra", "oxígeno", "ecosistema", "vegetación"],
    "Plantas Purificadoras": ["plantas", "purificar", "naturales", "aire", "interior", "hojas", "absorber", "toxinas", "ambiente", "decoración"],
    "Purificación pasiva (materiales de construcción)": ["materiales", "pasiva", "paredes", "pintura", "adsorción", "arquitectura", "ambiente", "absorber", "interior", "natural"],
    "Purificadores Caseros": ["casero", "hecho", "manual", "filtro", "básico", "materiales", "económico", "purificación", "aire", "botella"],
    "Quema de Combustibles Fósiles": ["combustibles", "fósiles", "quema", "co2", "emisión", "calor", "humo", "industria", "carbono", "vehículos"],
    "Reciclaje y Reutilización": ["reciclaje", "reutilización", "residuos", "clasificación", "aprovechar", "materiales", "uso", "basura", "separar", "reduce"],
    "Reducir Emisiones en Casa": ["emisiones", "hogar", "reducción", "aire", "cocina", "productos", "eficiencia", "energía", "evitar", "contaminación"],
    "Resiliencia climática": ["resiliencia", "climática", "adaptación", "impactos", "eventos", "mitigación", "riesgos", "sistemas", "variabilidad", "respuesta"],
    "Sensor BME688": ["bme688", "gas", "voc", "presión", "temperatura", "medición", "sensor", "ambiente", "aire", "detecta"],
    "Sensor MQ-7": ["mq-7", "monóxido", "co", "sensor", "reacción", "gas", "lectura", "toxicidad", "sensado", "dispositivo"],
    "Sensor PMS5003": ["pms5003", "pm", "partículas", "sensor", "aire", "medición", "lectura", "polvo", "ambiente", "dispositivo"],
    "Sistemas híbridos de purificación": ["sistemas", "híbrido", "purificación", "combinados", "filtros", "tecnologías", "integrados", "eficiencia", "sensor", "ventilación"],
    "Tecnología ambiental": ["tecnología", "ambiental", "innovación", "sensores", "sistemas", "monitoreo", "sostenible", "dispositivos", "impacto", "digital"],
    "Tráfico Vehicular": ["tráfico", "vehicular", "coches", "autos", "emisiones", "combustible", "calle", "movilidad", "aire", "ozono"],
    "UV y fotocatálisis": ["uv", "fotocatálisis", "luz", "reacción", "purificación", "fotónica", "material", "aire", "gases", "energía"],
    "Uso de Transporte Sostenible": ["transporte", "sostenible", "movilidad", "vehículos", "eficiencia", "alternativas", "bicicleta", "caminar", "público", "impacto"],
    "Uso de energías renovables": ["energías", "renovables", "solar", "eólica", "limpia", "alternativa", "reducción", "co2", "impacto", "medioambiente"],
    "Ventilación Natural": ["ventilación", "natural", "flujo", "ventanas", "renovación", "aire", "espacios", "ambiente", "corriente", "hogar"],
    "Ventilar Espacios": ["abrir", "ventanas", "espacios", "cerrados", "aire", "flujo", "purificación", "ambiente", "hogar", "renovación"],
    "agradecimientos": ["gracias", "te", "agradezco", "ayuda", "servicio", "respuesta", "asistencia", "útil", "favor", "valoración"],
    "despedidas": ["adiós", "hasta", "luego", "nos", "vemos", "cuídate", "gracias", "estés", "bien", "nuevamente"],
    "respuesta_positiva": ["correcto", "bien", "funciona", "gracias", "me", "sirvió", "perfecto", "eso", "era", "excelente"],
    "saludos": ["hola", "buenas", "saludos", "qué", "tal", "día", "cómo", "puedo", "ayudar", "estás"],
    "Índice de Calidad del Aire (AQI)": ["aqi", "índice", "calidad", "aire", "nivel", "escala", "categorías", "medición", "salud", "contaminación"]
};

module.exports = { PalabrasClave, PalabrasPorSubtema };